### ISSUE TITLE
Align Confirmation page with the other journey pages

### ISSUE THREAD

**Issue by christophercameron-ixd** [alphagov/forms-prototypes#53]
This page needs updating to align with the rest of the journey. 

Page title (that appears in the browser tab):

- [x] Update to the correct page name, "Edit confirmation - GOV.UK Forms" (This should reflect the Page title given by user if changed)
<img width="709" alt="Screenshot 2022-05-11 at 13 43 06" src="https://user-images.githubusercontent.com/35372982/167852430-2771ac56-0f5d-4df9-8a4e-44ce672f30af.png">

Main changes to editing area of the page:

- [x] Back button added
- [x] Green "Create a new page" button updated to "Save changes"
- [x] Link to "page list" needs moved to under green button
- [x] Link to "page list" content needs to be updated to "Go to form overview" (as per other pages)

Changes to in page preview area:

- [x] Add h2 "Page preview" (might need input from @hannahkc )
- [x] Remove "Open in a new tab" from preview frame
- [x] Add "Preview page in anew tab" as a link above the preview frame
- [x] Remove the "Update preview" link(?) from under the preview frame 

### As is screenshot
<img width="983" alt="Screenshot 2022-05-11 at 13 36 53" src="https://user-images.githubusercontent.com/35372982/167851315-0bca918d-f82e-48c8-a25d-cc027fadb8c6.png">

**Comment by hannahkc** [comment]
'Page preview' and 'Preview page in a new tab' are perfect. It's right to talk about a 'page' rather than a 'question' here. :)
