### ISSUE TITLE
There are no page templates yet

### ISSUE THREAD

**Issue by timpaul** [alphagov/forms-prototypes#7]
The 'page templates' option on the 'Choose a page type' screen doesn't actually work yet.

Each template will probably need a custom edit view.

For example, the 'Address' template will contain multiple fields, for each line of the address - not something that the 'from scratch' edit view could do.

**Comment by christophercameron-ixd** [comment]
Closing this issue for now. This is something that is on the trello backlog (ICEBOX?) to consider later in public beta
