### ISSUE TITLE
Remove "question short name" from edit pages

### ISSUE THREAD

**Issue by christophercameron-ixd** [alphagov/forms-prototypes#83]
We would like to remove the short name input from edit pages - we think it adds confusion and would like to test the impact of removing it.

We should use the long version across the service including, summaries (CYA, emails and form overview. 
The preview URL could use the long version replacing caps with lowercase, spaces with dashes ('-') and removing any other punctuation

**Comment by thomasiles** [comment]
I don't think it will cause many issues to remove it from the prototype, so it will be low effort.

When we made it optional in a previous round, we removed the need for it on the overview page so we don't need to make any changes there.

I'll have to check the CYA page, which might still use it, but changing that would be quick.
