### ISSUE TITLE
Add DRAFT / PREVIEW watermark to preview screens

### ISSUE THREAD

**Issue by christophercameron-ixd** [alphagov/forms-prototypes#84]
We want to try making it more obvious to users that they are viewing a DRAFT version of the form they are creating.

We hope this will help users understand where they are and hopefully prompt them to be able to mentally switch between editing/creating and previewing/testing.

We need to consider adding visually hidden text to the end of the page heading for example, "What is your name? preview"

Example of DRAFT background from publishing journey:
https://draft-origin.publishing.service.gov.uk/apply-national-insurance-number?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1MTgxZTQyNi1iNzU3LTQ5ZjItYWM4My0yYTYwMjg2OTQxYzciLCJjb250ZW50X2lkIjoiYjcwNTMxZDQtZTkwNC00YTk1LWE0ODAtMmRhZDVjMzIyY2E0IiwiaWF0IjoxNjU1NzU4ODgwLCJleHAiOjE2NTgzNTA4ODB9.HtXmH92DN7qY0pBmLNBrMWJuJml87lAE_6BEh2gvPTc

**Comment by christophercameron-ixd** [comment]
@hannahkc can we decide what the wording should be? Draft or Preview?

**Comment by hannahkc** [comment]
For the watermark? I had said that I think I'd prefer to use 'preview' so
we're consistent with what we're calling it. Though I imagine we'd perhaps
use 'draft' as a status for a form when we start showing those... So
actually, if draft will be consistent with that, it might be good to use
'Draft' for the watermark. As that will imply its a preview but also be
clear that it's not a live form.

For the hidden heading addition we should use preview.

Sound ok?
