### ISSUE TITLE
You have to manually refresh the page preview in edit mode

### ISSUE THREAD

**Issue by timpaul** [alphagov/forms-prototypes#9]
It might be nice if the page preview updated automatically as you filled out or changed the edit form.

Perhaps updated each time you moved focus from a field?

We'll need to decide if 'edit' pages only save updates when you hit a 'Save' button, or if they 'save as you go'.

**Comment by DavidBiddle** [comment]
I think there are a couple of ways we could do this while keeping the preview roughly the same. Both of these require JS so they'd have to be enhancements:

1. keep the preview as it is (an iframe to a separate preview page that depends on the saved state) and update the state  of the form via AJAX as the user types (or when they change field, or every few seconds). This might be unexpected for the user - would they necessarily expect every change they make in the editor to be saved without them actively saving it?
2. on devices that support this, swap the preview for something generated by JS from the current state of the fields on the page - this preview would represent 'what the form would look like if I saved', which is possibly more in line with what users might expect from a preview.

But there's also a question on what users need this preview for and whether we can serve these needs with something else. For instance:

- if users want to figure out what each field maps to on the form, some of this might be accomplished with content improvements (I think some of our UR participants have had ideas on this)
- if they want to see what each answer type does, maybe we need to think about how the answer type field is designed - this may also inform how we end up designing our 'component library'.

**Comment by thomasiles** [comment]
Both techniques for refreshing the preview sound reasonable.

I think there is definitely something to explore about the wider issue. I was surprised how little the users wanted/needed the inline preview when creating questions. I thought it would be essential. So far the (few) users who tested it didn't seem phased by not seeing the final form as they went along, wanting to check things in sections, maybe on the page list.

**Comment by christophercameron-ixd** [comment]
Closing this issue for now, as we are exploring the ability to preview screens in a different way without JS or inline previews
